version: 2
jobs:
  build:
    working_directory: ~/splitly
    docker:
      - image: circleci/node:6.10-browsers
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test
      - store_test_results:
          path: test-results.xml