version: 2
jobs:
  setup:
    working_directory: /home/circleci/splitly
    docker:
      - image: circleci/node:6.10-browsers
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Build production bundle
          command: npm run build:production
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace: 
          root: /home/circleci
          paths: 
            - splitly
      - store_artifacts:
          path: ./dist
  test:
    docker:
      - image: circleci/node:6.10-browsers
    working_directory: ~/splitly
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run tests
          command: npm run test
  e2e_test:
    docker:
      - image: circleci/node:6.10-browsers
    working_directory: ~/splitly
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run cypress e2e tests
          command: npm run cypress:ci
      - store_artifacts:
          path: ./cypress/videos

workflows:
  version: 2
  setup_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - e2e_test:
          requires:
            - setup